services:
  node-api:
    build: .
    image: ivancarlos/node-api:latest
    container_name: node-api
    hostname: node-api
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./config:/config   # persiste db.sqlite e api.env

    environment:
      - PUID=1000
      - PGID=1000
      - USER=ivan
      - GROUP=ivan
