---
version: '3'
services:
  xpto-server:
    image: ${IMAGE}:${META_TAG}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    working_dir: /home/${USER}
    ports: [8989:443, 8080:8080, 9418:9418]
    volumes:
      - ./system/opt/xpto-server:/opt/xpto-server
      - ./system/root/etc/services.d:/etc/services.d
      - ./home:/home/${USER}
      - ./repos:/srv/git
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - USER=${USER}
      - GROUP=${GROUP}
      - UID=${UID}
      - GID=${GID}
      - PORT=443
      - MESSAGE=Servidor XPTO respondendo pelo s6

    # env_file: env.production

    # ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    #  nofile:
    #    soft: 65536
    #    hard: 65536
    # mem_limit: 20M
    ##mem_limit: 20Mg
    # cpu_quota: 50000
    # cap_add:
    #  - IPC_LOCK
