---
version: '3'
services:
  xpto-server:
    image: ${IMAGE}:${META_TAG}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    working_dir: /home/${USER}
    # command: entrypoint.sh /bin/bash -l
    ports: [8989:443]
    volumes:
      - ./system/root/etc/cont-init.d:/etc/cont-init.d
      - ./system/opt/sdk:/opt/sdk
      - ./system/var/sdk:/var/sdk
      - ./system/etc/sdk:/etc/sdk
      - ${PWD}/home:/home/${USER}
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - USER=${USER}
      - GROUP=${GROUP}
      - UID=${UID}
      - GID=${GID}

    # env_file: env.production

    # ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    #  nofile:
    #    soft: 65536
    #    hard: 65536
    # mem_limit: 20M
    ##mem_limit: 20Mg
    # cpu_quota: 50000
    # cap_add:
    #  - IPC_LOCK
